export const authActionTypes = {
  LOGIN_START: "LOGIN_START",
  REGISTER_START: "REGISTER_START",
  GET_ME_START: "GET_ME_START",
  AUTHORIZATION_SUCCESS: "AUTHORIZATION_SUCCESS",
  AUTHORIZATION_FAILURE: "AUTHORIZATION_FAILURE",
};
