export const commentActionTypes = {
  ADD_POST_COMMENTS: "ADD_POST_COMMENTS",
  LOAD_POST_COMMENTS_LIST: "LOAD_POST_COMMENTS_LIST",
  LOAD_CURRENT_POST_COMMENTS: "LOAD_CURRENT_POST_COMMENTS",
  COMMENT_POST_START: "COMMENT_POST_START",
  ADD_COMMENT_TO_LIST: "ADD_COMMENT_TO_LIST",
  COMMENT_FAILURE: "COMMENT_FAILURE",
};
