export const settingsActionTypes = {
  GET_PROFILE_SETTINGS_START: "GET_PROFILE_SETTINGS_START",
  UPDATE_PROFILE_START: "UPDATE_PROFILE_START",
  GET_PROFILE_SETTINGS_SUCCESS: "GET_PROFILE_SETTINGS_SUCCESS",
  GET_FRIENDS_START: "GET_FRIENDS_START",
  GET_FRIENDS_SUCCESS: "GET_FRIENDS_SUCCESS",
  GET_MADE_REQUESTS_START: "GET_MADE_REQUESTS_START",
  GET_MADE_REQUESTS_SUCCESS: "GET_MADE_REQUESTS_SUCCESS",
  GET_RECEIVED_REQUESTS_START: "GET_RECEIVED_REQUESTS_START",
  GET_RECEIVED_REQUESTS_SUCCESS: "GET_RECEIVED_REQUESTS_SUCCESS",
  SETTINGS_ERROR: "SETTINGS_ERROR",
};
