export const settingsActionTypes = {
  GET_PROFILE_SETTINGS_START: "GET_PROFILE_SETTINGS_START",
  UPDATE_PROFILE_START: "UPDATE_PROFILE_START",
  GET_PROFILE_SETTINGS_SUCCESS: "GET_PROFILE_SETTINGS_SUCCESS",
  SETTINGS_ERROR: "SETTINGS_ERROR",
};
