export const profileActionTypes = {
  GET_PROFILE_START: "GET_PROFILE_START",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_POSTS_START: "GET_PROFILE_POSTS_START",
  GET_PROFILE_POSTS_SUCCESS: "GET_PROFILE_POSTS_SUCCESS",
  SEND_FRIEND_REQUEST_START: "SEND_FRIEND_REQUEST_START",
  CANCEL_FRIEND_REQUEST_START: "CANCEL_FRIEND_REQUEST_START",
  ACCEPT_FRIEND_REQUEST_START: "ACCEPT_FRIEND_REQUEST_START",
  REMOVE_FRIEND_START: "REMOVE_FRIEND_START",
  GET_FRIEND_LIST_START: "GET_FRIEND_LIST_START",
  GET_FRIEND_LIST_SUCCESS: "GET_FRIEND_LIST_SUCCESS",
  CLEAR_PROFILE_DATA: "CLEAR_PROFILE_DATA",
  PROFILE_FAILURE: "GET_PROFILE_FAILURE",
};
