export const profileActionTypes = {
  GET_PROFILE_START: "GET_PROFILE_START",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_POSTS_START: "GET_PROFILE_POSTS_START",
  GET_PROFILE_POSTS_SUCCESS: "GET_PROFILE_POSTS_SUCCESS",
  CLEAR_PROFILE_DATA: "CLEAR_PROFILE_DATA",
  PROFILE_FAILURE: "GET_PROFILE_FAILURE",
};
