export const postActionTypes = {
  GET_POSTS_LIST_START: "GET_POSTS_LIST_START",
  GET_POSTS_LIST_SUCCESS: "GET_POSTS_LIST_SUCCESS",
  GET_POSTS_LIST_FAILURE: "GET_POSTS_LIST_FAILURE",
  CREATE_POST_START: "CREATE_POST_START",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",
};
