export const friendsActionTypes = {
  SEND_FRIEND_REQUEST_START: "SEND_FRIEND_REQUEST_START",
  SEND_FRIEND_REQUEST_SUCCESS: "SEND_FRIEND_REQUEST_SUCCESS",
  CANCEL_FRIEND_REQUEST_START: "CANCEL_FRIEND_REQUEST_START",
  CANCEL_FRIEND_REQUEST_SUCCESS: "CANCEL_FRIEND_REQUEST_SUCCESS",
  ACCEPT_FRIEND_REQUEST_START: "ACCEPT_FRIEND_REQUEST_START",
  ACCEPT_FRIEND_REQUEST_SUCCESS: "ACCEPT_FRIEND_REQUEST_SUCCESS",
  REJECT_FRIEND_REQUEST_START: "REJECT_FRIEND_REQUEST_START",
  REJECT_FRIEND_REQUEST_SUCCESS: "REJECT_FRIEND_REQUEST_SUCCESS",
  REMOVE_FRIEND_START: "REMOVE_FRIEND_START",
  REMOVE_FRIEND_SUCCESS: "REMOVE_FRIEND_SUCCESS",
  FRIENDS_ACTIONS_FAILURE: "FRIENDS_ACTIONS_FAILURE",
};
