export const host = process.env.REACT_APP_HOST_URL || 'http://localhost:3000';

// Authorization actions
// credentials
export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
// login
export const LOGIN_REQUEST_PENDING = 'LOGIN_REQUEST_PENDING';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';
// register
export const REGISTER_REQUEST_PENDING = 'REGISTER_REQUEST_PENDING';
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAILED = 'REGISTER_REQUEST_FAILED';
// signout
export const SIGNOUT_REQUEST_PENDING = 'SIGNOUT_REQUEST_PENDING';
export const SIGNOUT_REQUEST_SUCCESS = 'SIGNOUT_REQUEST_SUCCESS';
export const SIGNOUT_REQUEST_FAILED = 'SIGNOUT_REQUEST_FAILED';
// login with token
export const LOGIN_WITH_TOKEN = 'LOGIN_WITH_TOKEN';
// get user
export const GET_USER_REQUEST_PENDING = 'GET_USER_REQUEST_PENDING';
export const GET_USER_REQUEST_SUCCESS = 'GET_USER_REQUEST_SUCCESS';
export const GET_USER_REQUEST_FAILED = 'GET_USER_REQUEST_FAILED';
// ----------------
// Load post list
export const GET_POSTS_REQUEST_PENDING = 'GET_POSTS_REQUEST_PENDING';
export const GET_POSTS_REQUEST_SUCCESS = 'GET_POSTS_REQUEST_SUCCESS';
export const GET_POSTS_REQUEST_FAILED = 'GET_POSTS_REQUEST_FAILED';
// Add post
export const ADD_POST_REQUEST_PENDING = 'ADD_POST_REQUEST_PENDING';
export const ADD_POST_REQUEST_SUCCESS = 'ADD_POST_REQUEST_SUCCESS';
export const ADD_POST_REQUEST_FAILED = 'ADD_POST_REQUEST_FAILED';
// Update post
export const UPDATE_POST_REQUEST_PENDING = 'UPDATE_POST_REQUEST_PENDING';
export const UPDATE_POST_REQUEST_SUCCESS = 'UPDATE_POST_REQUEST_SUCCESS';
export const UPDATE_POST_REQUEST_FAILED = 'UPDATE_POST_REQUEST_FAILED';
// Delete post
export const DELETE_POST_REQUEST_PENDING = 'DELETE_POST_REQUEST_PENDING';
export const DELETE_POST_REQUEST_SUCCESS = 'DELETE_POST_REQUEST_SUCCESS';
export const DELETE_POST_REQUEST_FAILED = 'DELETE_POST_REQUEST_FAILED';
// Change input data
export const CHANGE_HEADER = 'CHANGE_HEADER';
export const CHANGE_BODY = 'CHANGE_BODY';
// Get other user profile
export const GET_PROFILE_REQUEST_PENDING = 'GET_PROFILE_REQUEST_PENDING';
export const GET_PROFILE_REQUEST_SUCCESS = 'GET_PROFILE_REQUEST_SUCCESS';
export const GET_PROFILE_REQUEST_FAILED = 'GET_PROFILE_REQUEST_FAILED';
// clear profile state
export const CLEAR_PROFILE_STATE = 'CLEAR_PROFILE_STATE';
// ------
// Friends
export const FRIEND_REQUEST_PENDING = 'FRIEND_REQUEST_PENDING';
export const FRIEND_REQUEST_SUCCESS = 'FRIEND_REQUEST_SUCCESS';
export const FRIEND_REQUEST_FAILED = 'FRIEND_REQUEST_FAILED';
// Comments
// add
export const ADD_COMMENT_REQUEST_PENDING = 'ADD_COMMENT_REQUEST_PENDING';
export const ADD_COMMENT_REQUEST_SUCCESS = 'ADD_COMMENT_REQUEST_SUCCESS';
export const ADD_COMMENT_REQUEST_FAILED = 'ADD_COMMENT_REQUEST_FAILED';
// update
export const UPDATE_COMMENT_REQUEST_PENDING = 'UPDATE_COMMENT_REQUEST_PENDING';
export const UPDATE_COMMENT_REQUEST_SUCCESS = 'UPDATE_COMMENT_REQUEST_SUCCESS';
export const UPDATE_COMMENT_REQUEST_FAILED = 'UPDATE_COMMENT_REQUEST_FAILED';
// delete
export const DELETE_COMMENT_REQUEST_PENDING = 'DELETE_COMMENT_REQUEST_PENDING';
export const DELETE_COMMENT_REQUEST_SUCCESS = 'DELETE_COMMENT_REQUEST_SUCCESS';
export const DELETE_COMMENT_REQUEST_FAILED = 'DELETE_COMMENT_REQUEST_FAILED';